name: instagram
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  firebase_storage: ^12.4.4
  cloud_firestore: ^5.6.5
  uuid: ^4.5.1
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

  

flutter:
  uses-material-design: true

  assets:
    - assets/images/
