// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC69-HTMD0RZ3BEnGLta9PtyWBnZejYAk8',
    appId: '1:460682290900:web:f32a7432b60ae5499efd41',
    messagingSenderId: '460682290900',
    projectId: 'instagramclone-ba6ea',
    authDomain: 'instagramclone-ba6ea.firebaseapp.com',
    storageBucket: 'instagramclone-ba6ea.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4S3qRYMWTHdDI7X7YAXcqa2r824v1bW8',
    appId: '1:460682290900:android:0dd0d1c76c995c979efd41',
    messagingSenderId: '460682290900',
    projectId: 'instagramclone-ba6ea',
    storageBucket: 'instagramclone-ba6ea.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDc2YI_xhswlEUoM7qLoKDRhNqxUcunLY8',
    appId: '1:460682290900:ios:2b801bc0365217559efd41',
    messagingSenderId: '460682290900',
    projectId: 'instagramclone-ba6ea',
    storageBucket: 'instagramclone-ba6ea.firebasestorage.app',
    iosBundleId: 'com.example.instagram',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDc2YI_xhswlEUoM7qLoKDRhNqxUcunLY8',
    appId: '1:460682290900:ios:2b801bc0365217559efd41',
    messagingSenderId: '460682290900',
    projectId: 'instagramclone-ba6ea',
    storageBucket: 'instagramclone-ba6ea.firebasestorage.app',
    iosBundleId: 'com.example.instagram',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC69-HTMD0RZ3BEnGLta9PtyWBnZejYAk8',
    appId: '1:460682290900:web:afc5a05775f5359d9efd41',
    messagingSenderId: '460682290900',
    projectId: 'instagramclone-ba6ea',
    authDomain: 'instagramclone-ba6ea.firebaseapp.com',
    storageBucket: 'instagramclone-ba6ea.firebasestorage.app',
  );
}
